### ISSUE TITLE
Option to add custom CSS

### ISSUE THREAD

**Issue by itshimesh** [UtkarshVerma/startbootstrap-clean-blog#25]
First of all, thanks for such a clean, simple theme.

In terms of adding custom CSS, it would be nice if you could specify a param with custom css files. Some theme creaters have started doing this. You can see an example of how it is done here.

https://discuss.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4

**Comment by humboldtux** [comment]
Hi @itshimesh. This is an interesting feature, but not something i will use so i don't plan to add myself. PR welcome :smile:
